import json
import pandas as pd # Just for check? No need.
import os

file_path = r'c:\Yaraman(Data-Analyst)\Coffee Consumption - Copy\syrup.ipynb'

try:
    with open(file_path, 'r', encoding='utf-8') as f:
        notebook = json.load(f)

    new_cells = [
      {
       "cell_type": "code",
       "execution_count": None,
       "id": "app_logic_func",
       "metadata": {},
       "outputs": [],
       "source": [
        "# --- LOGIC PORTED FROM APP.PY ---\n",
        "\n",
        "def load_data():\n",
        "    try:\n",
        "        # Stock Take Sheet\n",
        "        sheet_id = \"1mKcRWrkCMHXOpofdjU1MrwRmhUGaaET8RUOG6eyHAqA\"\n",
        "        url = f\"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=xlsx\"\n",
        "        stock = pd.read_excel(url)\n",
        "        return stock\n",
        "    except Exception as e:\n",
        "        print(f\"Error loading Stock Data: {e}\")\n",
        "        return None\n",
        "\n",
        "def preprocess_data(stock):\n",
        "    if stock is None: return pd.DataFrame()\n",
        "    # Standardize columns\n",
        "    stock.columns = stock.columns.str.lower().str.strip()\n",
        "    \n",
        "    # Date conversion\n",
        "    if \"inventory date :\" in stock.columns:\n",
        "        stock[\"inventory date :\"] = pd.to_datetime(stock[\"inventory date :\"])\n",
        "        stock[\"month\"] = stock[\"inventory date :\"].dt.to_period(\"M\")\n",
        "    \n",
        "    return stock\n",
        "\n",
        "def get_stock_summary(stock):\n",
        "    if stock.empty: return pd.DataFrame()\n",
        "    # We need unique closing stock per item per month.\n",
        "    # Key columns for grouping - Group by Item Code and Month ONLY for uniqueness\n",
        "    group_cols = [\"item code :\", \"month\"]\n",
        "    \n",
        "    # Aggregation rules: Sum quantity, take first available description/category\n",
        "    agg_dict = {\n",
        "        \"physical quantity :\": \"sum\",\n",
        "        \"item name :\": \"first\",\n",
        "        \"category :\": \"first\",\n",
        "        \"uom :\": \"first\"\n",
        "    }\n",
        "    \n",
        "    # Filter agg_dict to only include columns present in df\n",
        "    agg_dict = {k: v for k, v in agg_dict.items() if k in stock.columns}\n",
        "    \n",
        "    # Aggregate\n",
        "    monthly_stock = stock.groupby(group_cols).agg(agg_dict).reset_index()\n",
        "    monthly_stock.rename(columns={\"physical quantity :\": \"closing_stock\"}, inplace=True)\n",
        "    \n",
        "    return monthly_stock\n",
        "\n",
        "def load_warehouse_data():\n",
        "    try:\n",
        "        # Warehouse Issues Sheet\n",
        "        sheet_id = \"1Cy0A4nQvbaW8GYlqyuiLvob-qed5Lu-GugPNGjSaGF4\"\n",
        "        url = f\"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=xlsx\"\n",
        "        warehouse = pd.read_excel(url)\n",
        "        return warehouse\n",
        "    except Exception as e:\n",
        "        print(f\"Error loading Warehouse Data: {e}\")\n",
        "        return None\n",
        "\n",
        "def preprocess_warehouse(warehouse):\n",
        "    if warehouse is None: return pd.DataFrame()\n",
        "    warehouse.columns = warehouse.columns.str.lower().str.strip()\n",
        "    if \"issue date :\" in warehouse.columns:\n",
        "        warehouse[\"issue date :\"] = pd.to_datetime(warehouse[\"issue date :\"])\n",
        "        warehouse[\"month\"] = warehouse[\"issue date :\"].dt.to_period(\"M\")\n",
        "    return warehouse\n",
        "\n",
        "def get_warehouse_summary(warehouse):\n",
        "    if warehouse.empty: return pd.DataFrame()\n",
        "    # Group by Item Code and Month to get total issued quantity\n",
        "    group_cols = [\"item code\", \"month\"]\n",
        "    \n",
        "    # Aggregation: Sum issue quantity\n",
        "    agg_dict = {\n",
        "        \"issue quantity :\": \"sum\"\n",
        "    }\n",
        "    \n",
        "    # Filter agg_dict\n",
        "    agg_dict = {k: v for k, v in agg_dict.items() if k in warehouse.columns}\n",
        "    \n",
        "    warehouse_summary = warehouse.groupby(group_cols).agg(agg_dict).reset_index()\n",
        "    warehouse_summary.rename(columns={\"issue quantity :\": \"supplied_qty\", \"item code\": \"item code :\"}, inplace=True)\n",
        "    \n",
        "    return warehouse_summary"
       ]
      },
      {
       "cell_type": "code",
       "execution_count": None,
       "id": "app_logic_exec",
       "metadata": {},
       "outputs": [],
       "source": [
        "# --- EXECUTION ---\n",
        "\n",
        "print(\"Loading Data... (This may take a moment)\")\n",
        "raw_stock = load_data()\n",
        "df_stock = preprocess_data(raw_stock)\n",
        "stock_summary = get_stock_summary(df_stock)\n",
        "\n",
        "raw_warehouse = load_warehouse_data()\n",
        "warehouse_df_raw = preprocess_warehouse(raw_warehouse)\n",
        "warehouse_summary = get_warehouse_summary(warehouse_df_raw)\n",
        "\n",
        "# Determine Month (Using Latest)\n",
        "if not df_stock.empty and \"month\" in df_stock.columns:\n",
        "    available_months = df_stock[\"month\"].unique().astype(str)\n",
        "    available_months = sorted(available_months, reverse=True)\n",
        "    selected_month_str = available_months[0] # Selecting Last Month\n",
        "    selected_month = pd.Period(selected_month_str, freq=\"M\")\n",
        "    print(f\"Analyzed Month: {selected_month_str}\")\n",
        "else:\n",
        "    print(\"No data found.\")\n",
        "    selected_month = None"
       ]
      },
      {
       "cell_type": "code",
       "execution_count": None,
       "id": "app_logic_calc",
       "metadata": {},
       "outputs": [],
       "source": [
        "if selected_month:\n",
        "    # Calculate Opening Stock (Previous Month Closing)\n",
        "    previous_month = selected_month - 1\n",
        "    prev_month_data = stock_summary[stock_summary[\"month\"] == previous_month].copy()\n",
        "    prev_month_data = prev_month_data.set_index(\"item code :\")\n",
        "    \n",
        "    # Current Month Closing\n",
        "    current_month_data = stock_summary[stock_summary[\"month\"] == selected_month].copy()\n",
        "    current_month_data = current_month_data.set_index(\"item code :\")\n",
        "\n",
        "    # Current Month Supply\n",
        "    current_month_supply = warehouse_summary[warehouse_summary[\"month\"] == selected_month].copy()\n",
        "    current_month_supply = current_month_supply.set_index(\"item code :\")\n",
        "\n",
        "    # Master Data Construction (Opening + Closing + Supply)\n",
        "    # Union of all relevant items\n",
        "    all_items = prev_month_data.index.union(current_month_supply.index).union(current_month_data.index)\n",
        "    \n",
        "    master_df = pd.DataFrame(index=all_items)\n",
        "    \n",
        "    # Metadata Map\n",
        "    # Map item names from stock data first (most reliable)\n",
        "    master_item_map = df_stock[[\"item code :\", \"item name :\", \"category :\", \"uom :\"]].drop_duplicates(\"item code :\")\n",
        "    master_item_map = master_item_map.set_index(\"item code :\")\n",
        "    \n",
        "    master_df = master_df.join(master_item_map, how=\"left\")\n",
        "    master_df.rename(columns={\"item name :\": \"Item Name\", \"category :\": \"Category\", \"uom :\": \"UOM\"}, inplace=True)\n",
        "    \n",
        "    # Fill Data\n",
        "    master_df[\"Opening Stock\"] = prev_month_data[\"closing_stock\"]\n",
        "    master_df[\"Supplied Qty\"] = current_month_supply[\"supplied_qty\"]\n",
        "    master_df[\"Closing Stock\"] = current_month_data[\"closing_stock\"]\n",
        "    \n",
        "    master_df.fillna(0, inplace=True)\n",
        "    \n",
        "    # Consumption Logic\n",
        "    master_df[\"Total Available\"] = master_df[\"Opening Stock\"] + master_df[\"Supplied Qty\"]\n",
        "    master_df[\"Consumption\"] = master_df[\"Total Available\"] - master_df[\"Closing Stock\"]\n",
        "\n",
        "    master_df.index.name = \"Item Code\"\n",
        "    master_df = master_df.reset_index()\n",
        "\n",
        "    # --- SYRUP FILTER ---\n",
        "    syrup_df = master_df[master_df[\"Category\"].astype(str).str.contains(\"SYRUP\", case=False, na=False)].copy()\n",
        "\n",
        "    print(\"\\n🍯 SYRUP INVENTORY & ACTUAL CONSUMPTION\")\n",
        "    cols = [\"Item Name\", \"Opening Stock\", \"Supplied Qty\", \"Total Available\", \"Closing Stock\", \"Consumption\", \"UOM\"]\n",
        "    syrup_final = syrup_df[cols].sort_values(\"Consumption\", ascending=False)\n",
        "    display(syrup_final)"
       ]
      }
    ]

    notebook['cells'].extend(new_cells)

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=1)

    print("Notebook updated successfully.")
except Exception as e:
    print(f"Error: {e}")
